#! /usr/bin/env python
# encoding: utf-8
make(locals())

def options(opt):
    opt.add_option("--rampapp",
                   action = "store_true",
                   default = False,
                   help = u"allows building of the application for ramp analysis")

def build(bld, __old__= locals()['build']):
    __old__(bld)
    if bld.options.rampapp :
        bld.program(source = ["mainramp.cpp"],
                    includes = ["."],
                    target = "../../ramp/mainramp.exe",
                    install_path = "",
                    vnum = "0.1")
