buildgcc:
  stage: build
  script:
    - conda list --explicit
    - export CXX=g++-8
    - python waf configure --cxxflags "-std=c++17 -g -Werror"
    - python waf build

buildclang:
  stage: build
  script:
    - export CXX=clang++
    - python waf configure --cxxflags "-std=c++17 -g -Werror"
    - python waf build --nolinting

unittest:
  stage: unittest
  script: 
    - export CXX=g++-8
    - python waf configure
    - python waf build --nolinting
    - python waf test --unittests

integrationtest:
  stage: integrationtest
  script: 
    - export CXX=g++-8
    - python waf configure
    - python waf build --nolinting
    - python waf test --alltests --coverage
