buildgcc:
  stage: build
  script:
    - export CXX=g++-8
    - python waf clean
    - python waf configure --cxxflags "-std=c++17 -g -Werror"
    - python waf build

buildclang:
  stage: build
  script:
    - export CXX=clang++
    - python waf clean
    - python waf configure --cxxflags "-std=c++17 -g -Werror"
    - python waf build --nolinting

test:
  stage: test
  script: 
    - export CXX=g++-8
    - python waf clean
    - python waf configure --cxxflags "-std=c++17 -g -Werror"
    - python waf build --nolinting
    - cd build
    - pytest tests/*.py
