name: trackanalysis
channels: !!python/tuple
- defaults
dependencies:
- bokeh=0.12.3=py35_0
- click=6.6=py35_0
- conda-forge::flexx=0.4.1=py35_0
- conda-forge::pandas=0.19.1=np111py35_0
- fklab::pybind11=1.9a1=py35_0
- python=3.5.2=0
