#!/usr/bin/env python3
# -*- coding: utf-8 -*-
u"Calls on waf directly: this is a link which both windows and git can understand"
import sys
from importlib import import_module
sys.path.insert(0, "./wafbuilder/bin")
import_module("call_waf")
