import wafbuilder as builder

require('python', pytest = '3.0.4', rtime  = False)

def build(bld):
    name  = builder.appname()
    pysrc = bld.path.ant_glob('**/*.py')
    builder.checkpy  (bld, 'tests', pysrc)
    builder.copyfiles(bld, builder.appname(), pysrc)

make()
