#!/usr/bin/env python3
# encoding: utf-8
import wafbuilder as builder

require(
    'python',
    pytest      = '3.0.4',
    coverage    = '4.5.3',
    selenium    = '3.141.0',
    geckodriver = '0.24.0',
    rtime       = False
)

require(nodejs = '10.13.0',                  rtime = False)
require(nodejs = dict(typescript = '3.4.4'), rtime = False)

def build(bld):
    pysrc = bld.path.ant_glob('**/*.py')
    cfe   = bld.path.ant_glob('**/*.ts')

    builder.checkpy  (bld, 'tests', pysrc, 'pylint')
    builder.copyfiles(bld, builder.appname(), pysrc)
    builder.copyfiles(bld, builder.appname(), cfe)

make(locals())
