require(python = dict(nodejs = '6.6.0', flexx = '0.4.1', bokeh = '0.12.4'), rtime = True)
require(coffee = '1.10.0',                                                  rtime = True)
make(builders = ['python', 'coffee'])
