require(python = dict(nodejs = '6.6.0', flexx = '0.4.1', bokeh = '0.12.6'), rtime = True)
require(coffee = '1.10.0',                                                  rtime = False)
make(locals())

@patch
def postfix_build(bld):
    bld.transfer_static_html()
