import makescripts
make(locals())

def startscripts(bld):
    "creates start scripts"
    bld.make_startup_script('hybridstat', 'hybridstat.view.HybridStatView')

@patch
def post_build(bld):
    makescripts.build_bokehjs(bld, APPNAME)
