import wafbuilder

require(python = dict(bokeh = '0.12.16'), rtime = True)
require(coffee = '1.10.0', rtime = False)
make(builders = ['python', 'coffee'])

@patch
def postfix_build(bld):
    bld.transfer_static_html()
