import wafbuilder

require(python = dict(bokeh = '0.12.5'), rtime = True)
require(coffee = '1.10.0', rtime = False)
make(builders = ['python', 'coffee'])

@patch
def postfix_build(bld):
    files = bld.path.ant_glob(['static/*.css', 'static/*.js', 'static/*.map'])
    wafbuilder.copyfiles(bld, 'static', files)
