import makescripts
make(locals())

def startscripts(bld):
    "creates start scripts"
    bld.make_startup_script('cyclesplot', 'cyclesplot.CyclesPlotView')

@patch
def post_build(bld):
    makescripts.build_bokehjs(bld, APPNAME)
